name: Go linters

on:
  push:

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          check-latest: true
